### ISSUE TITLE
论重写该项目的必要性 ヾ(•ω•`)o

### ISSUE THREAD

**Issue by NebuDr1ft** [azaz-az/holiday-predictor#2]
首先感谢仓库已有的贡献者对这个小工具的维护—— (❁´◡`❁)

这个小工具的确有它的实践价值，在许多情况下都是很有用的工具。不过程序仍然存在一些亟待优化的点，也有一些肉眼可见的不完美之处。如果这些地方都能够完善，那么这个工具就更能在用户手上发光发热。(*/ω＼*)

然而，问题在于，这个小工具的源代码有点过于混乱，这无疑会给其他贡献者的维护造成很大的困扰。比如，我今天想要给小工具新增功能，但是光理解源代码就耗费了几个小时的时间。代码过于冗余且混乱是开源社区中非常致命的一点——因为对于他人来说，理解就是一件耗费时间的事，而再在其上做出一些修改，则更给人无从下手的感觉。

就拿函数 `forecast_chl` 举例吧。原代码中，传入的参数 `holiday_name` 似乎并没有起到很大的作用——因为函数主要逻辑中，它是通过全局变量 `user_input_list` 来工作的。那么这样的传参就是完全没用的，它和把函数主体写在代码主体里面是等效的。既然我们要重构出一个函数，那就应该让它真正具备一点函数的特性。除此之外，还有一些不太符合 Python 主流代码风格的地方，在这里就不一一说明了。

总而言之，我个人认为，重写该项目是必要的，这样可以增进这个小工具代码的可读性和可维护性。对于此，我尝试重写了一份小工具的代码 [NebuDr1ft/holiday-predictor](https://github.com/NebuDr1ft/holiday-predictor)，但因才疏学浅，难免有疏漏之处。如果您认为我的代码有借鉴价值，那我很高兴能够通过 Pull Request 贡献仓库，为小工具的建设增砖添瓦。

以上。祝好。

Nebu Dr1ft
2024/2/17

**Comment by azaz-az** [comment]
首先感谢你的issue和修改。

        我已经查看了你修改后的代码，个人认为，你的修改确实很好，有借鉴价值。希望你能够将你的修改提交 Pull Request，我将会 Merge 你的修改。

        此致
敬礼。

azaz-az
2024/2/18

**Comment by NebuDr1ft** [comment]
我将相关事宜已经发送至您的邮箱，您可以选择合并我的 Pull Request。

如果没有什么特别需要注明的，我将关闭该 issue。
