### ISSUE TITLE
建议在setup.py中添加语句

### ISSUE THREAD

**Issue by CHUA-X** [azaz-az/holiday-predictor#27]
我在Python 3.8中安装您的模块时报UnicodeDecodeError错误：

![新建位图图像](https://github.com/azaz-az/holiday-predictor/assets/163215295/bc2b89ec-ecf3-434e-ba00-695eeaa329dd)

建议把setup.py中“with open("README.md", "r") as fh:”改为：
with open("README.md", "r", encoding='utf-8') as fh:

望采纳。

**Comment by azaz-az** [comment]
好的，同意采纳本建议，现在正在处理

**Comment by azaz-az** [comment]
已在 develop 分支中更改。正在合并到 master 并发布至 PyPI

**Comment by azaz-az** [comment]
已采纳本建议，并处理完毕，合并到 master 分支，上传至 PyPI. 

最后，感谢你的建议。
